// frontend/udlånssystem/src/components/breadcrumbs.tsx
import { useLocation, useNavigate } from "react-router-dom";
import { Fragment } from "react/jsx-runtime";

import { formatPathToBreadcrumbs } from "@services/pathFormatter";

export default function Breadcrumbs() {
  const location = useLocation();
  const navigate = useNavigate();

  function handleClick(inputpath: string) {
    if (location.pathname === inputpath) return;

    navigate(inputpath, { replace: true });
  }

  return (
    <div className="p-2">
      <div className="box-border flex w-full items-center gap-2 rounded-[10px] bg-base-200 p-[3px]">
        {formatPathToBreadcrumbs(location.pathname).map((path, i: number) => (
          <Fragment key={i}>
            <button
              onClick={() => {
                handleClick(path.fullPath);
              }}
              className="cursor-pointer rounded-xl border-none bg-transparent p-[0.4rem_1rem] text-base font-medium underline transition-colors duration-100 ease-in-out"
            >
              <p>{path.path}</p>
            </button>

            {path.seperator && <i className="fa-solid fa-angles-right" />}
          </Fragment>
        ))}
      </div>
    </div>
  );
}

// frontend/udlånssystem/src/components/breadcrumbs.svelte
<script>
  import { path } from "../stores/pathStore";
  import { formatPathToBreadcrumbs } from "../services/pathFormatter.js";
  import { navigate } from "svelte-routing";

  function handleClick(inputpath) {
    if (currentPath === inputpath) return;

    path.update(() => {
      return inputpath;
    });

    navigate(inputpath, { replace: true });
  }

  $: currentPath = $path;
</script>

<div class="content">
  {#each formatPathToBreadcrumbs(currentPath) as path}
    <button
      on:click={() => {
        handleClick(path.fullPath);
      }}
    >
      <p>{path.path}</p>
    </button>
    <!-- seperation icon -->
    {#if path.seperator}
      <i class="fa-solid fa-angles-right" />
    {/if}
  {/each}
</div>

<style>
  .content {
    box-sizing: border-box;
    display: flex;
    align-items: center;
    gap: 0.5rem;
    width: 100%;
    background-color: var(--bg2);
    border-radius: 10px;
    padding: 3px;
  }
  button {
    background: none;
    text-decoration: underline;
    border: none;
    color: var(--text2);
    font-size: 1rem;
    font-weight: 500;
    cursor: pointer;
    border-radius: 10px;
    transition: background-color 100ms ease-in-out;
    padding: 0.4rem 1rem;
  }
</style>
