// frontend/udlånssystem/src/components/form-edit-panel.svelte
<script>
  export let editMode = false;
  import { createEventDispatcher } from "svelte";
  const dispatch = createEventDispatcher();
  //create reset event
  function handleReset() {
    dispatch("reset");
    editMode = !editMode;
  }
  //create update event
  function handleUpdate() {
    dispatch("update");
  }
  //create delete event
  function handleDelete() {
    dispatch("delete");
  }
  function handleCancel() {
    dispatch("cancel");
  }
</script>

<div class="control-panel">
  <div class="buttons">
    {#if editMode}
      <button disabled={!editMode} on:click={handleReset}>Annuller</button>
      <button on:click={handleUpdate}>Gem</button>
    {:else}
      <button on:click={handleCancel}>Tilbage</button>
      <button
        on:click={() => {
          editMode = !editMode;
        }}>Rediger</button
      >
    {/if}
  </div>
  {#if editMode}
    <button id="delete" on:click={handleDelete}>Slet</button>
  {/if}
</div>

<style>
  button:hover {
    background-color: #5b596e;
    scale: 0.98;
  }
  #delete {
    color: white;
    background: #f85a40dd;
  }
</style>

// frontend/udlånssystem/src/components/form-edit-panel.tsx
import '@styles/controlPanel.css';

export default function FormEditPanel({
  editMode = false,
  setEditMode = (value: any) => {},
  disableDelete = false,
  handleReset = () => {},
  handleUpdate = () => {},
  handleDelete = () => {},
  handleCancel = () => {},
  editPanelSlot = <></>,
  formSlot = <></>,
  children = <></>,
}) {
  return (
    <div className="control-panel">
      <div className="buttons">
        {editMode ? (
          <>
            <button disabled={!editMode} onClick={handleReset}>
              Annuller
            </button>
            <button onClick={handleUpdate}>Gem</button>
          </>
        ) : (
          <>
            <button onClick={handleCancel}>Tilbage</button>
            <button
              onClick={() => {
                setEditMode(!editMode);
              }}
            >
              Rediger
            </button>
          </>
        )}
      </div>
      {editMode && (
        <button
          className="text-[#f85a40dd] text-white"
          onClick={handleDelete}
          disabled={disableDelete}
        >
          Slet
        </button>
      )}
      {children}
    </div>
  );
}
