// frontend/udlånssystem/src/components/Nav-menu.svelte
<script>
  import { navigate } from "svelte-routing";
  import { path } from "../stores/pathStore";
  import { fly } from "svelte/transition";
  import { stripPath } from "../services/pathFormatter";
  export let text = "Home";
  export let icon = "fa-solid fa-house";
  export let buttons = [
    {
      text: "",
      icon: "",
      destination: "/",
    },
  ];

  //subscription to path store
  $: currentPath = $path;

  //update path store and navigate to destination
  function handleNavClick(dest) {
    path.update(() => {
      return dest;
    });

    navigate(dest, { replace: true });
  }
  //toggle menu
  function handleMenuClick() {
    open = !open;

    if (open) {
      scrollIntoView(buttons[buttons.length - 1].text);
    }
  }
  let open = false;

  //scroll to element when menu is opened
  function scrollIntoView(classname) {
    setTimeout(() => {
      const el = document.getElementById(classname);
      if (!el) return;

      el.scrollIntoView({
        behavior: "smooth",
      });
    }, 10);
  }
</script>

<button
  class:selected={!open &&
    buttons.some((button) => button.destination === currentPath)}
  class="outer"
  on:click={handleMenuClick}
>
  <div class="flex large between">
    <div class="flex">
      <i class={icon} />
      <p>{text}</p>
    </div>

    <i class:closed={!open} class="fa-solid fa-angle-up" />
  </div>
</button>
{#if open}
  <div class="buttons" transition:fly={{ y: -20, duration: 200 }}>
    {#each buttons as button}
      <button
        class:selected={stripPath(currentPath, 1) === button.destination}
        class="selected"
        id={button.text}
        on:click={() => {
          handleNavClick(button.destination);
        }}
      >
        <div class="flex small">
          {#if button.icon}
            <i class={button.icon} />
          {/if}
          <p>{button.text}</p>
        </div>
      </button>
    {/each}
  </div>
{/if}

<style>
  button {
    background: none;
    width: 100%;
    border: none;
    border-radius: 10px;
    transition: background-color 100ms ease-in-out;
    cursor: pointer;
  }
  button.outer {
    padding: 0;
    cursor: pointer;
  }
  .large {
    padding: 0.7rem 1rem;
  }
  .small {
    padding: 0.5rem 1rem;
  }
  .between {
    justify-content: space-between !important;
  }
  .buttons {
    width: 100%;
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    padding-left: 4rem;
  }
  .show {
    height: auto;
  }
  /* Target buttons hover if not selected */
  button:hover:not(.selected) {
    background-color: var(--bg2);
    box-shadow:
      rgba(0, 0, 0, 0.25) 0px 0.0625em 0.0625em,
      rgba(0, 0, 0, 0.25) 0px 0.125em 0.5em,
      rgba(255, 255, 255, 0.1) 0px 0px 0px 1px inset;
  }
  .flex {
    display: flex;
    align-items: center;
    justify-content: flex-start;
    gap: 0.5rem;
  }
  .closed {
    transform: rotate(180deg);
  }
  .selected {
    background-color: var(--p);
  }
  .selected p,
  .selected i {
    color: #fff !important;
  }
  i {
    font-size: 1.25rem;
    width: 2rem;
    color: var(--text3);
    transition: transform 150ms ease-in-out;
  }
  p {
    font-size: 1.2rem;
    color: var(--text3);
  }
</style>

// frontend/udlånssystem/src/components/Nav-menu.tsx
import { useEffect, useState } from 'react';
import { NavLink, useLocation, useNavigate } from 'react-router-dom';

import '@styles/navMenu.css';

export default function NavMenu({
  text = 'Home',
  icon = 'fa-solid fa-house',
  buttons = [
    {
      text: '',
      icon: '',
      destination: '/',
    },
  ],
}) {
  const location = useLocation();
  const navigate = useNavigate();

  const [open, setOpen] = useState(false);

  function handleNavClick(dest: string) {
    navigate(dest, { replace: true });
  }

  //toggle menu
  function handleMenuClick() {
    setOpen(!open);
  }

  useEffect(() => {
    if (open) {
      scrollIntoView2(buttons[buttons.length - 1].text);
    }
  }, [open]);

  //scroll to element when menu is opened
  function scrollIntoView2(classname: string) {
    setTimeout(() => {
      const el = document.getElementById(classname);
      if (!el) return;

      el.scrollIntoView({
        behavior: 'smooth',
      });
    }, 10);
  }

  function isClosed() {
    return !open ? 'rotate-180' : '';
  }

  function isSelected(button: any) {
    return location.pathname == button.destination ? 'selected' : '';
  }

  return (
    <>
      <button
        // class:selected={!open &&
        //   buttons.some((button) => button.destination === location.pathname)}
        className="w-full cursor-pointer rounded-[10px] p-0 transition-colors duration-100 ease-in-out"
        onClick={handleMenuClick}
      >
        <div className="flex items-center justify-between gap-2 p-[0.7rem_1rem]">
          <div className="flex items-center justify-start gap-2">
            <i className={icon} />
            <p className="text-[1.2rem] text-foreground3">{text}</p>
          </div>

          <i className={'fa-solid fa-angle-up ' + isClosed()} />
        </div>
      </button>

      {open && (
        <div
          className="flex w-full flex-col gap-2 pl-16"
          // transition:fly={{ y: -20, duration: 200 }}
        >
          {buttons.map((button, i) => (
            <NavLink
              key={i}
              className={
                'w-full cursor-pointer rounded-[10px] p-0 text-center transition-colors duration-100 ease-in-out ' +
                isSelected(button)
              }
              id={button.text}
              to={button.destination}
            >
              <div className="flex items-center justify-start gap-2 p-[0.5rem_1rem]">
                {button.icon && <i className={button.icon} />}
                <p className="text-[1.2rem] text-foreground3">{button.text}</p>
              </div>
            </NavLink>
          ))}
        </div>
      )}
    </>
  );
}
