// frontend/udlånssystem/src/components/selectQuestion.tsx
import { useEffect } from 'react';

interface SelectQuestionProps {
  editMode?: boolean;
  label: string;
  setValue?: (value: any) => void;
  match?: { UUID: number };
  options?: { UUID: number; name: string }[];
}

export default function SelectQuestion({
  editMode = true,
  label,
  setValue = () => {},
  match = { UUID: 1 },
  options = [{ UUID: 1, name: '' }],
}: SelectQuestionProps) {
  useEffect(() => {
    if (options.length <= 0) return;

    setValue(options[0].UUID);
  }, [options]);

  return (
    <div className="question">
      <label htmlFor="a10">
        {label}
        {editMode && <span className="required-tag">*</span>}
      </label>
      <select
        disabled={!editMode}
        id="a10"
        required
        form="user-form"
        className="!py-0"
        onChange={(e) => {
          setValue(JSON.parse(e.target.value));
        }}
        defaultValue={JSON.stringify(match.UUID)}
      >
        {options.map((option, i) => (
          <option key={i} value={JSON.stringify(option.UUID)}>
            {option.name}
          </option>
        ))}
      </select>
    </div>
  );
}

// frontend/udlånssystem/src/components/selectQuestion.svelte
<!-- ! good luck if this ever breaks! -->
<!-- it took almost a week to get it to work. -->
<!-- 70 201 201 - nummeret til livlinien. du for brug for det. -->
<script>
// @ts-nocheck

  export let editMode = true;
  export let label;
  export let binding = 1;
  export let match = { UUID: 1, name: "" };
  export let options = [{ UUID: 1, name: "" }];
</script>

<div class="question">
  <label for="a10"
    >{label} <span class="required-tag" class:hidden={!editMode}>*</span></label
  >
  <select
    disabled={!editMode}
    id="a10"
    required
    form="user-form"
    on:change={(e) => {
      binding = JSON.parse(e.target.value);
    }}
  >
    {#each options as option}
      <option
        selected={option.UUID == match.UUID}
        value={JSON.stringify(option.UUID)}
        >{option.name}
      </option>
    {/each}
  </select>
</div>
