// frontend/udlånssystem/src/components/textQuestion.svelte
<script>
  export let editMode = true;
  export let label;
  export let type = "text";
  export let binding;
  export let required = true;
  export let placeholder = "";
</script>

<div class="question">
  <label for="text">
    {label}
    {#if required}
      <span class="required-tag" class:hidden={!editMode}>*</span>
    {/if}
  </label>
  {#if type === "text"}
    <input
      autocomplete="off"
      disabled={!editMode}
      bind:value={binding}
      class="text"
      type="text"
      {placeholder}
      {required}
    />
  {:else if type === "number"}
    <input
      autocomplete="off"
      disabled={!editMode}
      bind:value={binding}
      class={`text ${editMode ? "hover:disabled" : ""}`}
      type="number"
      {placeholder}
      {required}
    />
  {:else if type === "password"}
    <input
      autocomplete="off"
      disabled={!editMode}
      bind:value={binding}
      class="text"
      type="password"
      {required}
    />
  {/if}
</div>

// frontend/udlånssystem/src/components/textQuestion.tsx
interface TextQuestionProps {
  editMode?: boolean;
  label: string;
  type?: 'text' | 'number' | 'password';
  value?: string | number;
  setValue?: (value: any) => void;
  required?: boolean;
  placeholder?: string;
  disabled?: boolean;
}

export default function TextQuestion({
  editMode = true,
  label,
  type = 'text',
  value = '',
  setValue = (_value: any) => {},
  required = true,
  placeholder = '',
  disabled = false,
}: TextQuestionProps) {
  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    let newValue: string | number = e.target.value;

    if (type === 'number') newValue = Number(newValue);

    setValue(newValue);
  }

  return (
    <div className="question">
      <label htmlFor="text">
        {label}
        {required && editMode && !disabled && (
          <span className={'required-tag'}>*</span>
        )}
      </label>

      <input
        autoComplete="off"
        disabled={!editMode || disabled}
        value={value}
        onChange={handleChange}
        className="text"
        type={type}
        placeholder={placeholder}
        required={required}
      />
    </div>
  );
}
