// frontend/udlånssystem/src/components/user-widget.tsx
import { useContext } from 'react';

import { logout } from '@services/login';

import { CurrentUserContext } from '@/App';

export default function UserWidget() {
  const { currentUser: user, setCurrentUser } = useContext(CurrentUserContext);

  if (!user) return null;

  return (
    <div className="flex h-20 w-full items-center justify-between rounded-2xl border-[1px] border-solid border-foreground bg-base-200 px-4 py-[0.8rem]">
      <div className="flex gap-4">
        <div className="flex flex-col justify-evenly">
          <h3 className="text-[1.1rem] font-medium text-foreground">
            {user.firstName} {user.lastName}
          </h3>
          <p className="text-[0.9rem] text-foreground2">{user.username}</p>
        </div>
      </div>

      <div className="flex h-full content-start">
        <i
          id="logout"
          onClick={() => logout(setCurrentUser)}
          className="fa-solid fa-arrow-right-from-bracket cursor-pointer"
        />
      </div>
    </div>
  );
}

// frontend/udlånssystem/src/components/user-widget.svelte
<script>
  import { currentUser } from "../services/login";
  import { logout } from "../services/login";

  $: user = $currentUser;
</script>

<div class="content">
  <div class="info">
    {#if user}
      <!-- <img src={user.img_name ? pic : profilePic} alt="profilePic" /> -->
    {:else}
      <!-- <img src={profilePic} alt="" /> -->
    {/if}
    {#if user}
      <div class="text">
        <h3>{user.name || "Søren"}</h3>
        <p>{user.username || "søren69420"}</p>
      </div>
    {:else}
      <h3>{"Søren"}</h3>
      <p>{"søren69420"}</p>
    {/if}
  </div>

  <div class="more">
    <i on:click={logout} class="fa-solid fa-arrow-right-from-bracket" />
  </div>
</div>

<style>
  .content {
    display: flex;
    justify-content: space-between;
    background: var(--bg2);
    border-radius: 15px;
    width: 100%;
    border: solid 1px var(--text1);
    align-items: center;
    padding: 0.8rem 1rem;
    height: 80px;
  }
  .text {
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
  }
  .info {
    display: flex;
    gap: 1rem;
  }
  .more {
    display: flex;
    align-content: start;
    height: 100%;
  }
  img {
    width: 50px;
    height: 50px;
    border-radius: 50%;
    border: solid 1px var(--text1);
  }
  p {
    color: var(--text2);
    font-size: 0.9rem;
  }
  h3 {
    color: var(--text1);
    font-weight: 500;
    font-size: 1.1rem;
  }
  i {
    cursor: pointer;
  }
</style>
