// frontend/udlånssystem/src/pages/udlaan/return/index.tsx
import { useEffect, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";

import Table from "@components/table";

import getData from "@data/getData";
import { columnsFormatter } from "@helpers/tableHelpers";
import useBarcode from "@hooks/useBarcode";
import useData from "@hooks/useData";

import axios from "axios";
import { toast } from "sonner";

import "@styles/return.css";

const exclude = [
  "date_returned",
  "loan_id",
  "Stregkode",
  "Returneret",
  "Med_taske",
  "Med_Laas",
];

export default function Return() {
  const { id } = useParams();

  const navigate = useNavigate();

  const [searchParams, setSearchParams] = useSearchParams();

  const [itemsLent, setItemsLent] = useState<itemsFromLoan[]>([]);
  const [itemsReturning, setItemsReturning] = useState<itemsFromLoan[]>([]);
  const [itemsReturned, setItemsReturned] = useState<itemsFromLoan[]>([]);

  const [products] = useData<itemsFromLoan[]>("items_from_loans");

  useEffect(() => {
    const initItem = searchParams.get("item");

    if (initItem) {
      const item = products?.find(({ UUID }) => UUID.toString() == initItem);

      if (item) {
        handleAddProduct(item);
        setSearchParams("");
      }
    }
  }, [products]);

  useBarcode(handleBarcode);

  async function handleBarcode(code: string) {
    let findProduct = itemsReturning.find(({ Stregkode }) => Stregkode == code);

    if (findProduct) {
      toast.error(`${findProduct.Produkt} er allerede tilføjet`);
      return;
    }

    findProduct = itemsLent.find(({ Stregkode }) => Stregkode == code);

    if (findProduct) {
      toast.success(`${findProduct.Produkt} tilføjet`);
      handleAddProduct(findProduct);
      return;
    }

    let getItemsFromLoans = await getData<any>(
      `items_from_loans?Stregkode=${code}&Returneret=null`,
      { withHeaders: false },
    );

    findProduct = getItemsFromLoans[0];

    if (findProduct) {
      toast.error(`${findProduct.Produkt} lånt ud på et andet lån`);
      return;
    }

    toast.error("Produktet kunne ikke findes");
  }

  async function importDataFromDB() {
    const items = await getData<itemsFromLoan[]>(
      "items_from_loans?loan_id=" + id,
    );

    if (!items) return;

    setItemsLent(items.filter((item) => !item.Returneret));
    setItemsReturned(items.filter((item) => item.Returneret));
  }

  function handleAddProduct(product: itemsFromLoan) {
    if (itemsLent.length == 0) return;

    const tempReturn = [...itemsReturning];
    const tempLent = [...itemsLent];

    const productIndex = tempLent.findIndex(({ UUID }) => UUID == product.UUID);

    if (productIndex == -1) return;

    tempReturn.push(tempLent.splice(productIndex, 1)[0]);

    setItemsReturning(tempReturn);
    setItemsLent(tempLent);
  }

  function handleRemoveProduct(product: itemsFromLoan) {
    const tempReturn = [...itemsReturning];
    const tempLent = [...itemsLent];

    const productIndex = tempReturn.findIndex(
      ({ UUID }) => UUID == product.UUID,
    );

    tempLent.push(tempReturn.splice(productIndex, 1)[0]);

    setItemsReturning(tempReturn);
    setItemsLent(tempLent);
  }

  async function handleReturn() {
    if (itemsReturning.length > 0) {
      const updatePromise = axios.patch("loans/return/item", {
        ItemsInLoanToReturn: itemsReturning,
      });

      toast.promise(updatePromise, {
        loading: "Returnerer produkter...",
        success: "Produkterne er returneret",
        error: "Der skete en fejl",
      });
    }

    navigate(`/udlaan`);
  }
  function handleAddAll() {
    setItemsReturning(itemsLent);
    setItemsLent([]);
  }

  useEffect(() => {
    importDataFromDB();
  }, []);

  const columns = columnsFormatter<itemsFromLoan>(
    Object.keys(itemsLent[0] || itemsReturning[0] || itemsReturned[0] || {}),
  );

  return (
    <div className="returnLoan relative max-h-full overflow-y-scroll pb-16">
      {(itemsReturning.length != 0 || itemsLent.length != 0) && (
        <div className="max-h-half relative mt-8 grid h-max grid-cols-2 gap-4 pt-16">
          <div className="seperation seperation-1 absolute left-1/2 h-full border-r-2" />
          <div className="col-start-1">
            {itemsLent?.length > 0 && (
              <Table
                data={itemsLent}
                columns={columns || []}
                exclude={exclude}
                onRowClick={handleAddProduct}
                withFilters={false}
              />
            )}
          </div>
          <div className="col-start-2">
            {itemsReturning?.length > 0 ? (
              <Table
                data={itemsReturning}
                columns={columns || []}
                exclude={exclude}
                onRowClick={handleRemoveProduct}
                withFilters={false}
              />
            ) : (
              <p className="text-center">Tryk for at vælge produkter</p>
            )}
          </div>
        </div>
      )}

      <div className="mt-16 flex flex-col items-center justify-center gap-2">
        {(itemsLent.length != 0 || itemsReturning.length != 0) && (
          <>
            <button
              onClick={handleAddAll}
              id="add-all"
              disabled={itemsLent.length < 1}
            >
              Tilføj alle
            </button>
            <button
              onClick={handleReturn}
              id="return"
              disabled={!itemsReturning.length}
            >
              Returner valgte
            </button>
          </>
        )}

        <h1 className="mt-16 text-xl">Returnerede produkter</h1>
        <hr className="w-full" />

        <Table
          data={itemsReturned}
          columns={columns || []}
          exclude={exclude}
          withFilters={false}
        />
      </div>
    </div>
  );
}

// frontend/udlånssystem/src/pages/loans/return.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import TableSimplified from "../../components/table-simplified.svelte";

  import getData from "../../data/getData";
  import goToPath from "../../services/goToPath";

  export let id;

  let importItemsInLoanLent: itemsFromLoan[] = [];
  let importItemsInLoanAvailable: itemsFromLoan[] = [];
  let ItemsInLoanToReturn: itemsFromLoan[] = [];

  let importCablesInLoanLent: cableFromLoan[] = [];
  let importCablesInLoanAvailable: cableFromLoan[] = [];
  let CablesInLoanToReturn: cableFromLoan[] = [];

  // $: console.log("importItemsInLoanLent", importItemsInLoanLent);

  let table = "items_from_loans";
  let page_name = "Udlaan/returner";

  onMount(async () => {
    importDataFromDB();
  });

  import { barcodeStore, controlStore } from "../../stores/barcodeStore";
  import axios from "axios";
  function handleBarcode(code) {
    if (!$barcodeStore) return;

    //check if barcode is being added or removed
    if (!$controlStore) {
      if (importItemsInLoanLent.length == 0) return;
      const product = importItemsInLoanLent.find(
        ({ Barcode }) => Barcode == code
      );

      if (ItemsInLoanToReturn.find(({ Barcode }) => Barcode == code))
        return alert("Produktet er allerede tilføjet");

      if (!product) return alert("Produktet findes ikke");

      handleAddProduct({ detail: product });
      barcodeStore.set("");
    } else {
      const product = ItemsInLoanToReturn.find(
        ({ Barcode }) => Barcode == code
      );

      if (!product) return;

      if (importItemsInLoanLent.find(({ Barcode }) => Barcode == code)) return;

      handleRemoveProduct({ detail: product });
      barcodeStore.set("");
    }
  }
  $: handleBarcode($barcodeStore), importItemsInLoanLent;

  async function importDataFromDB() {
    const items = (await getData(table + "?loan_id=" + id)).data;
    const cables = (await getData("cables_from_loans?loan_id=" + id)).data;

    importItemsInLoanLent = items.filter(({ Returneret }) => !Returneret);
    importItemsInLoanAvailable = items.filter(({ Returneret }) => Returneret);

    importCablesInLoanLent = cables.filter((o) => o["Mængde lånt"] > 0);
    importCablesInLoanAvailable = cables.filter((o) => !(o["Mængde lånt"] > 0));
  }
  function handleAddProduct(event) {
    //move product from inputDataProducts to products
    let product = event.detail;
    if (importItemsInLoanLent.length == 0) return;

    ItemsInLoanToReturn.push(
      importItemsInLoanLent.splice(importItemsInLoanLent.indexOf(product), 1)[0]
    );
    ItemsInLoanToReturn = ItemsInLoanToReturn;
    importItemsInLoanLent = importItemsInLoanLent;
  }

  function handleRemoveProduct(event) {
    //move product from products to inputDataProducts
    let product = event.detail;
    importItemsInLoanLent.push(
      ItemsInLoanToReturn.splice(ItemsInLoanToReturn.indexOf(product), 1)[0]
    );
    ItemsInLoanToReturn = ItemsInLoanToReturn;
    importItemsInLoanLent = importItemsInLoanLent;
  }

  function handleAddCable(event) {
    //move product from importProducts to products'
    let cable = event.detail;
    if (importCablesInLoanLent.length == 0) return;

    cable["Mængde lånt"]--;
    cable["Mængde returneret"]++;

    const thisCable = CablesInLoanToReturn.find(
      ({ UUID }) => UUID == cable.UUID
    );
    var indexCable = CablesInLoanToReturn.find(({ UUID }) => UUID > cable.UUID);

    if (thisCable) {
      if (cable["Mængde lånt"] == 0)
        importCablesInLoanLent.splice(
          importCablesInLoanLent.indexOf(cable),
          1
        )[0];
    } else {
      if (cable["Mængde lånt"] == 0)
        CablesInLoanToReturn.splice(
          CablesInLoanToReturn.indexOf(indexCable),
          0,
          importCablesInLoanLent.splice(
            importCablesInLoanLent.indexOf(cable),
            1
          )[0]
        );
      if (cable["Mængde lånt"] >= 1)
        CablesInLoanToReturn.splice(
          CablesInLoanToReturn.indexOf(indexCable),
          0,
          cable
        );
    }

    CablesInLoanToReturn = CablesInLoanToReturn;
    importCablesInLoanLent = importCablesInLoanLent;
  }
  function handleRemoveCable(event) {
    //move product from products to importProducts
    let cable = event.detail;
    if (CablesInLoanToReturn.length == 0) return;

    cable["Mængde lånt"]++;
    cable["Mængde returneret"]--;

    const thisCable = importCablesInLoanLent.find(
      ({ UUID }) => UUID == cable.UUID
    );
    var indexCable = importCablesInLoanLent.find(
      ({ UUID }) => UUID > cable.UUID
    );

    if (thisCable) {
      if (cable["Mængde returneret"] == 0)
        CablesInLoanToReturn.splice(CablesInLoanToReturn.indexOf(cable), 1)[0];
    } else {
      if (cable["Mængde returneret"] == 0)
        importCablesInLoanLent.splice(
          importCablesInLoanLent.indexOf(indexCable),
          0,
          CablesInLoanToReturn.splice(CablesInLoanToReturn.indexOf(cable), 1)[0]
        );
      if (cable["Mængde returneret"] >= 1)
        importCablesInLoanLent.splice(
          importCablesInLoanLent.indexOf(indexCable),
          0,
          cable
        );
    }

    CablesInLoanToReturn = CablesInLoanToReturn;
    importCablesInLoanLent = importCablesInLoanLent;
  }

  async function handleReturn() {
    if (ItemsInLoanToReturn.length > 0) {
      const { status } = await axios.patch("loans/return/item", {
        ItemsInLoanToReturn,
      });

      if (status != 200) return alert("Der skete en fejl");

      alert("Produkterne er returneret");
    }

    if (CablesInLoanToReturn.length > 0) {
      const { status } = await axios.patch("loans/return/cable", {
        CablesInLoanToReturn,
      });

      if (status != 200) return alert("Der skete en fejl");

      alert("Kablerne er returneret");
    }

    goToPath(`/udlaan`);
  }
  function handleAddAll() {
    ItemsInLoanToReturn = importItemsInLoanLent;
    importItemsInLoanLent = [];
  }
</script>

<div class="overflow-y-scroll relative max-h-full pb-16">
  {#if ItemsInLoanToReturn.length != 0 || importItemsInLoanLent.length != 0}
    <div class="grid grid-cols-2 gap-4 max-h-half relative pt-16 mt-8 h-max">
      <div
        class="h-full border-r-2 seperation seperation-1 absolute left-1/2"
      />
      {#if importItemsInLoanLent?.length > 0}
        <div class="col-start-1">
          <TableSimplified
            on:message={handleAddProduct}
            inputData={importItemsInLoanLent}
            title=""
            exclude={["date_returned", "loan_id", "Barcode"]}
          />
        </div>
      {/if}
      <div class="col-start-2">
        {#if ItemsInLoanToReturn?.length > 0}
          <TableSimplified
            on:message={handleRemoveProduct}
            inputData={ItemsInLoanToReturn}
            title=""
            exclude={["date_returned", "loan_id", "Barcode"]}
          />
        {:else}
          <p class="text-center">Tryk på at vælge prokuter</p>
        {/if}
      </div>
    </div>
  {/if}
  {#if CablesInLoanToReturn.length != 0 || importCablesInLoanLent.length != 0}
    <div class="grid grid-cols-2 gap-4 max-h-half relative pt-16 mt-8 h-max">
      <div
        class="h-full border-r-2 seperation seperation-2 absolute left-1/2"
      />
      {#if importCablesInLoanLent?.length > 0}
        <div class="col-start-1">
          <TableSimplified
            on:message={handleAddCable}
            inputData={importCablesInLoanLent}
            title=""
            exclude={["date_returned", "loan_id", "Barcode"]}
          />
        </div>
      {/if}
      <div class="col-start-2">
        {#if CablesInLoanToReturn?.length > 0}
          <TableSimplified
            on:message={handleRemoveCable}
            inputData={CablesInLoanToReturn}
            title=""
            exclude={["date_returned", "loan_id", "Barcode"]}
          />
        {:else}
          <p class="text-center">Tryk for at vælge prokuter</p>
        {/if}
      </div>
    </div>
  {/if}

  <div class="flex justify-center mt-16 flex-col items-center gap-2">
    {#if ItemsInLoanToReturn.length != 0 || importItemsInLoanLent.length != 0 || CablesInLoanToReturn.length != 0 || importCablesInLoanLent.length != 0}
      <button
        on:click={handleAddAll}
        id="add-all"
        disabled={importItemsInLoanLent.length < 1}
      >
        Tilføj alle
      </button>
      <button
        on:click={handleReturn}
        id="return"
        disabled={!ItemsInLoanToReturn.length && !CablesInLoanToReturn.length}
      >
        returner valgte
      </button>
    {/if}
    {#if importItemsInLoanAvailable.length > 0}
      <h1 class="mt-16 text-xl">Returnerede produkter</h1>
      <hr class="w-full" />
      <TableSimplified
        on:message={handleAddProduct}
        inputData={importItemsInLoanAvailable}
        title=""
        disabled={true}
      />
    {/if}
    {#if importCablesInLoanAvailable.length > 0}
      <h1 class="mt-16 text-xl">Returnerede kabler</h1>
      <hr class="w-full" />
      <TableSimplified
        on:message={handleAddProduct}
        inputData={importCablesInLoanAvailable}
        title=""
        disabled={true}
      />
    {/if}
  </div>
</div>

<style>
  /* .max-h-half {
    max-height: 50vh;
  } */
  button {
    width: 100%;
    max-width: 400px;
    min-height: 2rem;
    height: 2rem;
    color: var(--text1);
    border: 1px solid var(--text1);
    border-radius: 10px;
    transition: all 0.2s ease-in-out;
  }
  button#return:hover {
    color: var(--s);
    border-color: var(--s);
    outline: none;
  }
  button#return {
    background: var(--text1);
    color: var(--bg1);
  }

  button:focus {
    outline: none;
  }
  button:disabled {
    color: var(--text1);
    border-color: var(--text1);
    cursor: not-allowed;
    opacity: 0.5;
  }
  .seperation {
    border-color: var(--text1);
  }
  .seperation-1::after {
    content: "Til retunering";
    position: absolute;
    width: max-content;
    top: 0;
    left: 20px;
    z-index: 2;
  }
  .seperation-1::before {
    content: "Udlånte produkter";
    position: absolute;
    top: 0;
    width: max-content;
    right: 20px;
    z-index: 2;
  }
  .seperation-2::before {
    content: "Udlånte kabler";
    position: absolute;
    top: 0;
    width: max-content;
    right: 20px;
    z-index: 2;
  }
  .seperation-2::after {
    content: "Til retunering";
    position: absolute;
    width: max-content;
    top: 0;
    left: 20px;
    z-index: 2;
  }
</style>
