// frontend/udlånssystem/src/layouts/edit.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import FormEditPanel from '@components/form-edit-panel';
import SelectQuestion from '@components/selectQuestion';
import TextQuestion from '@components/textQuestion';

import { deleteItem, getData, updateItem } from '@data/index.js';
import { autoGenZodSchema } from '@services/autoGen';
import doesObjectsMatch from '@services/doesObjectsMatch.js';
import { getPrevPage } from '@services/pathFormatter';

import { toast } from 'sonner';
import type { z } from 'zod';

const defaultFields: Field[] = [{ label: 'Navn', binding: 'name' }];

interface EditLayoutProps {
  table: string;
  fields?: Field[];
  zodSchema?: z.ZodObject<any>;
  editPanelSlot?: React.ReactElement;
  formSlot?: React.ReactElement;
}

export default function EditLayout({
  table,
  fields = defaultFields,
  zodSchema = autoGenZodSchema(fields),
  editPanelSlot = <></>,
  formSlot = <></>,
}: EditLayoutProps) {
  const { id } = useParams();
  const UUID = Number(id!);

  const navigate = useNavigate();

  const [editMode, setEditMode] = useState(false);

  const [importData, setImportData] = useState<any>();
  const [exportData, setExportData] = useState<any>();

  const [fields2, setFields] = useState(fields);

  async function fetchSelectOptions() {
    for (let field of fields) {
      if (field.type == 'select') {
        if (typeof field.options != 'string') continue;

        field.options = await getData<any>(field.options);
        setFields((prev) => [...prev]);
      }
    }

    setFields(fields);
  }

  // $: fetchSelectOptions(), fields;

  useEffect(() => {
    importDataFromDB();
  }, []);

  useEffect(() => {
    fetchSelectOptions();
  }, [fields2]);

  async function importDataFromDB() {
    const data = await getData<any>(table, { UUID });

    if (!data?.UUID) {
      toast.error('Kunne ikke finde data');
      navigate(getPrevPage());
      return;
    }

    setExportData({ ...data });
    setImportData({ ...data });

    fetchSelectOptions();
  }

  function isDeleteDisabled(): boolean {
    if (!importData?._count) return false;

    const { _count } = importData as { _count: { [key: string]: number } };

    for (let value of Object.values(_count)) {
      if (value > 0) return true;
    }

    return false;
  }

  async function handleUpdate(): Promise<void> {
    if (doesObjectsMatch(importData, exportData)) {
      setEditMode(false);
      return;
    }

    const { data, error } = zodSchema.safeParse(exportData);

    if (error) {
      error.errors.reverse().map((e) =>
        toast.warning(e.message, {
          id: e.code + '-' + e.path.join('-'),
        }),
      );
      return;
    }

    toast.promise(updateItem(table, UUID, data), {
      loading: 'Gemmer...',
      success: () => {
        importDataFromDB();
        setEditMode(false);
        return 'Gemt';
      },
      error: (err: any) => {
        console.log(err);
        return 'Der opstod en fejl';
      },
    });
  }

  async function handleDelete() {
    const name = importData?.name || '#' + UUID;

    toast(`Sikker på du vil slette "${name}"?`, {
      id: 'promptDelete',
      position: 'top-center',
      action: {
        label: 'Slet',
        onClick: () => {
          toast.promise(deleteItem({ UUID, table }), {
            loading: 'Sletter...',
            success: () => {
              navigate(getPrevPage());
              return 'Slettet';
            },
            error: (err: any) => {
              return 'Fejl: ' + err?.response?.data?.error;
            },
          });
        },
      },
      cancel: {
        label: 'Annuller',
        onClick: () => toast.dismiss('promptDelete'),
      },
    });
  }

  if (!importData) return <div>Loading...</div>;

  return (
    <div className="box-border flex h-full gap-4 p-8">
      <FormEditPanel
        handleReset={() => {
          importDataFromDB();
          setEditMode(false);
        }}
        handleCancel={() => {
          navigate(getPrevPage());
        }}
        handleDelete={handleDelete}
        handleUpdate={handleUpdate}
        editMode={editMode}
        setEditMode={setEditMode}
        disableDelete={isDeleteDisabled()}
      >
        {editPanelSlot}
      </FormEditPanel>
      <div
        onSubmit={(e) => {
          e.preventDefault;
          handleUpdate();
        }}
        className="form"
      >
        <form id="edit-form">
          {fields2.map((field, i) => {
            if (field.type == 'text' || field.type == 'number')
              return (
                <TextQuestion
                  key={i}
                  value={exportData[field.binding] || undefined}
                  setValue={(value) =>
                    setExportData((prev: any) => {
                      prev[field.binding] = value;
                      return { ...prev };
                    })
                  }
                  editMode={editMode}
                  label={field.label}
                  required={field.required}
                  type={field.type}
                  disabled={field.disabled}
                />
              );

            if (field.type == 'select' && typeof field.options == 'object')
              return (
                <SelectQuestion
                  key={i}
                  setValue={(value) =>
                    setExportData((prev: any) => {
                      prev[field.binding] = value;
                      return prev;
                    })
                  }
                  label={field.label}
                  options={field?.options}
                  match={{ UUID: exportData[field.binding] }}
                  editMode={editMode}
                />
              );
          })}
          {formSlot}
        </form>
      </div>
    </div>
  );
}

// frontend/udlånssystem/src/layouts/edit.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { deleteItem, updateItem, getData } from "@data/index.js";
  import TextQuestion from "@components/textQuestion.svelte";
  import NumberQuestion from "@components/numberQuestion.svelte";
  import SelectQuestion from "@components/selectQuestion.svelte";
  import FormEditPanel from "@components/form-edit-panel.svelte";
  import goToPath from "@services/goToPath.js";
  import doesObjectsMatch from "@services/doesObjectsMatch.js";
  import { toast } from "svelte-sonner";
  import type { z } from "zod";
  import type { Field } from "types/field";

  //this is the id of the brand to be edited
  export let UUID: number;
  export let table: string;
  export let page_name: string;

  export let zodSchema: z.ZodObject<any>;
  export let fields: Field[];

  //if the page is in edit mode or read only
  let editMode = false;

  //imported Data
  let importData;
  let exportData;

  onMount(async () => {
    try {
      importDataFromDB();
    } catch (error) {
      console.log(error);
    }
  });

  //loop to fetch select options in fields, where options is type of string
  async function fetchSelectOptions() {
    for (let field of fields) {
      if (field.type == "select") {
        if (!(typeof field.options == "string")) continue;

        const { data } = await getData(field.options);
        field.options = data;
      }
    }

    fields = [...fields];
  }

  $: fetchSelectOptions(), fields;

  async function importDataFromDB() {
    const data = await getData(table, UUID);

    if (!data?.UUID) {
      toast.error("Kunne ikke finde data");
      goToPath(`/${page_name.toLowerCase()}`);
      return;
    }
    exportData = { ...data };
    importData = { ...data };
  }

  function isDeleteDisabled(): boolean {
    if (!importData?._count) return false;

    const { _count } = importData as { _count: { [key: string]: number } };

    for (let value of Object.values(_count)) {
      if (value > 0) return true;
    }
  }

  async function handleUpdate(): Promise<void> {
    if (doesObjectsMatch(importData, exportData)) {
      editMode = false;
      return;
    }

    const { data, error } = zodSchema.safeParse(exportData);

    if (error) {
      error.errors.reverse().map((e) =>
        toast.warning(e.message, {
          id: e.code + "-" + e.path.join("-"),
        })
      );
      return;
    }

    toast.promise(updateItem(table, UUID, data), {
      loading: "Gemmer...",
      success: () => {
        importDataFromDB();
        editMode = false;
        return "Gemt";
      },
      error: (err: any) => {
        console.log(err);
        return "Der opstod en fejl";
      },
    });
  }

  async function handleDelete() {
    const name = importData?.name || "#" + UUID;

    toast(`Sikker på du vil slette "${name}"?`, {
      id: "promptDelete",
      action: {
        label: "Slet",
        onClick: () => {
          toast.promise(deleteItem({ UUID, table }), {
            loading: "Sletter...",
            success: () => {
              goToPath(`/${page_name.toLowerCase()}`);
              return "Slettet";
            },
            error: (err: any) => {
              return "Fejl: " + err?.response?.data?.error;
            },
          });
        },
      },
      cancel: { label: "Annuller" },
    });
  }
</script>

<!-- disableDelete={importData._count.products > 0} -->
{#if importData}
  <div class="content">
    <FormEditPanel
      on:reset={() => {
        importDataFromDB();
      }}
      on:cancel={() => {
        goToPath(`/${page_name.toLowerCase()}`);
      }}
      on:delete={handleDelete}
      on:update={handleUpdate}
      bind:editMode
      disableDelete={isDeleteDisabled()}
    >
      <slot name="edit-panel" />
    </FormEditPanel>
    <div
      on:submit={(e) => {
        e.preventDefault;
        handleUpdate();
      }}
      class="form"
    >
      <form id="edit-form">
        {#each fields as field}
          {#if field.type == "text" || field.type == "number"}
            <TextQuestion
              bind:binding={exportData[field.binding]}
              label={field.label}
              {editMode}
              required={field.required}
              type={field.type}
            />
          {:else if field.type == "select" && typeof field.options == "object"}
            <SelectQuestion
              bind:binding={exportData[field.binding]}
              label={field.label}
              options={field?.options}
              match={{ UUID: exportData[field.binding] }}
              {editMode}
            />
          {/if}
        {/each}
        <slot name="form" />
      </form>
    </div>
  </div>
{/if}

<style>
  .content {
    height: 100%;
    box-sizing: border-box;
    padding: 2rem;
    display: flex;
    gap: 1rem;
  }
</style>
