// frontend/udlånssystem/src/pages/cableCategories/edit.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { itemModel } from "../../types/itemModel.js";
  import TextQuestion from "../../components/textQuestion.svelte";
  import SelectQuestion from "../../components/selectQuestion.svelte";
  import deleteItem from "../../data/delete.js";
  import update from "../../data/update.js";
  import FormEditPanel from "../../components/form-edit-panel.svelte";
  import goToPath from "../../services/goToPath.js";
  import doesObjectsMatch from "../../services/doesObjectsMatch.js";
  import getData from "../../data/getData.js";

  import { barcodeStore } from "../../stores/barcodeStore.js";
  $barcodeStore = ""; //reset the barcode store. This is to prevent automatic redirect on load

  //this is the id of the item to be edited
  export let id;

  //if the page is in edit mode or read only
  let editMode = false;

  //imported Data
  let importData: any;
  let exportData: any;

  let table = "cable_categories";
  let page_name = "Kabelgrupper";

  let cableLoan = { loan_id: "" };
  let cableCategories = [];

  async function importDataFromDB() {
    let data = await getData(table, id);

    // HOT FIX - if the data is not found, redirect to the index page
    if (!data?.UUID) {
      if (data) alert("Kunne ikke hente data: " + data);
      goToPath(`/${page_name.toLowerCase()}`);
      return;
    }
    exportData = { ...data };
    importData = { ...data };
  }

  async function handleUpdate(): Promise<any> {
    if (doesObjectsMatch(importData, exportData)) {
      alert("Ingen ændringer");
      return;
    }

    const response: any = await update(exportData, table);
    if (response && response.success) {
      importDataFromDB();
      editMode = false;
      alert("Changes saved");
    } else {
      alert("Error 500 - Ukendt fejl");
    }
  }

  async function handleDelete() {
    const response: any = await deleteItem({
      UUID: importData.UUID,
      table,
    });
    console.log(response);
    if (response?.success) {
      alert("Slettet");
      goToPath(`/${page_name.toLowerCase()}`);
    } else {
      alert("Error 500 - Ukendt fejl");
    }
  }

  function handleSubmit(event) {
    event.preventDefault();
    handleUpdate();
  }
  import { path } from "../../stores/pathStore.js";
  // $: console.log($path);

  onMount(async () => {
    cableCategories = await getData("cable_categories");
    if (id) {
      importDataFromDB();
    }
  });
</script>

{#if importData}
  <div class="content">
    <FormEditPanel
      on:cancel={() => {
        goToPath(`/${page_name.toLowerCase()}`);
      }}
      on:reset={importDataFromDB}
      on:delete={handleDelete}
      on:update={handleUpdate}
      bind:editMode
      loanId={cableLoan?.loan_id}
      item={exportData}
    />
    <div
      on:submit={(e) => {
        e.preventDefault;
        handleUpdate();
      }}
      class="form"
    >
      <form id="user-form">
        <TextQuestion
          label="Navn"
          type="text"
          bind:binding={exportData.name}
          {editMode}
          required
        />
      </form>
    </div>
  </div>
{/if}

<style>
  .content {
    height: 100%;
    box-sizing: border-box;
    padding: 2rem;
    display: flex;
    gap: 1rem;
  }
</style>

// frontend/udlånssystem/src/layouts/edit.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import FormEditPanel from '@components/form-edit-panel';
import SelectQuestion from '@components/selectQuestion';
import TextQuestion from '@components/textQuestion';

import { deleteItem, getData, updateItem } from '@data/index.js';
import { autoGenZodSchema } from '@services/autoGen';
import doesObjectsMatch from '@services/doesObjectsMatch.js';
import { getPrevPage } from '@services/pathFormatter';

import { toast } from 'sonner';
import type { z } from 'zod';

const defaultFields: Field[] = [{ label: 'Navn', binding: 'name' }];

interface EditLayoutProps {
  table: string;
  fields?: Field[];
  zodSchema?: z.ZodObject<any>;
  editPanelSlot?: React.ReactElement;
  formSlot?: React.ReactElement;
}

export default function EditLayout({
  table,
  fields = defaultFields,
  zodSchema = autoGenZodSchema(fields),
  editPanelSlot = <></>,
  formSlot = <></>,
}: EditLayoutProps) {
  const { id } = useParams();
  const UUID = Number(id!);

  const navigate = useNavigate();

  const [editMode, setEditMode] = useState(false);

  const [importData, setImportData] = useState<any>();
  const [exportData, setExportData] = useState<any>();

  const [fields2, setFields] = useState(fields);

  async function fetchSelectOptions() {
    for (let field of fields) {
      if (field.type == 'select') {
        if (typeof field.options != 'string') continue;

        field.options = await getData<any>(field.options);
        setFields((prev) => [...prev]);
      }
    }

    setFields(fields);
  }

  // $: fetchSelectOptions(), fields;

  useEffect(() => {
    importDataFromDB();
  }, []);

  useEffect(() => {
    fetchSelectOptions();
  }, [fields2]);

  async function importDataFromDB() {
    const data = await getData<any>(table, { UUID });

    if (!data?.UUID) {
      toast.error('Kunne ikke finde data');
      navigate(getPrevPage());
      return;
    }

    setExportData({ ...data });
    setImportData({ ...data });

    fetchSelectOptions();
  }

  function isDeleteDisabled(): boolean {
    if (!importData?._count) return false;

    const { _count } = importData as { _count: { [key: string]: number } };

    for (let value of Object.values(_count)) {
      if (value > 0) return true;
    }

    return false;
  }

  async function handleUpdate(): Promise<void> {
    if (doesObjectsMatch(importData, exportData)) {
      setEditMode(false);
      return;
    }

    const { data, error } = zodSchema.safeParse(exportData);

    if (error) {
      error.errors.reverse().map((e) =>
        toast.warning(e.message, {
          id: e.code + '-' + e.path.join('-'),
        }),
      );
      return;
    }

    toast.promise(updateItem(table, UUID, data), {
      loading: 'Gemmer...',
      success: () => {
        importDataFromDB();
        setEditMode(false);
        return 'Gemt';
      },
      error: (err: any) => {
        console.log(err);
        return 'Der opstod en fejl';
      },
    });
  }

  async function handleDelete() {
    const name = importData?.name || '#' + UUID;

    toast(`Sikker på du vil slette "${name}"?`, {
      id: 'promptDelete',
      position: 'top-center',
      action: {
        label: 'Slet',
        onClick: () => {
          toast.promise(deleteItem({ UUID, table }), {
            loading: 'Sletter...',
            success: () => {
              navigate(getPrevPage());
              return 'Slettet';
            },
            error: (err: any) => {
              return 'Fejl: ' + err?.response?.data?.error;
            },
          });
        },
      },
      cancel: {
        label: 'Annuller',
        onClick: () => toast.dismiss('promptDelete'),
      },
    });
  }

  if (!importData) return <div>Loading...</div>;

  return (
    <div className="box-border flex h-full gap-4 p-8">
      <FormEditPanel
        handleReset={() => {
          importDataFromDB();
          setEditMode(false);
        }}
        handleCancel={() => {
          navigate(getPrevPage());
        }}
        handleDelete={handleDelete}
        handleUpdate={handleUpdate}
        editMode={editMode}
        setEditMode={setEditMode}
        disableDelete={isDeleteDisabled()}
      >
        {editPanelSlot}
      </FormEditPanel>
      <div
        onSubmit={(e) => {
          e.preventDefault;
          handleUpdate();
        }}
        className="form"
      >
        <form id="edit-form">
          {fields2.map((field, i) => {
            if (field.type == 'text' || field.type == 'number')
              return (
                <TextQuestion
                  key={i}
                  value={exportData[field.binding] || undefined}
                  setValue={(value) =>
                    setExportData((prev: any) => {
                      prev[field.binding] = value;
                      return { ...prev };
                    })
                  }
                  editMode={editMode}
                  label={field.label}
                  required={field.required}
                  type={field.type}
                  disabled={field.disabled}
                />
              );

            if (field.type == 'select' && typeof field.options == 'object')
              return (
                <SelectQuestion
                  key={i}
                  setValue={(value) =>
                    setExportData((prev: any) => {
                      prev[field.binding] = value;
                      return prev;
                    })
                  }
                  label={field.label}
                  options={field?.options}
                  match={{ UUID: exportData[field.binding] }}
                  editMode={editMode}
                />
              );
          })}
          {formSlot}
        </form>
      </div>
    </div>
  );
}
