// frontend/udlånssystem/src/pages/Error404.svelte
<div class="content">
  <h1>Error 404</h1>
  <p>Page not found</p>
  <img class="svg" src="svg/error404.svg" alt="Error 404" />
</div>

<style>
  .svg {
    width: 60%;
  }
  .content {
    padding-top: 5rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    height: 100%;
    overflow-y: auto;
  }
  p {
    color: var(--text2);
  }
</style>

// frontend/udlånssystem/src/pages/Error404.tsx
export default function Error404() {
  return (
    <div className="flex h-full flex-col items-center gap-2 overflow-y-auto pt-20">
      <h1>Error 404</h1>
      <p className="text-foreground2">Page not found</p>
      <img className="w-3/5" src="svg/error404.svg" alt="Error 404" />
    </div>
  );
}
