// frontend/udlånssystem/src/pages/Home.tsx
import { useNavigate } from 'react-router-dom';

import useBarcode from '@hooks/useBarcode';
import { cheatCode } from '@services/cheatCode';

import getData from '@/data/getData';
import { toast } from 'sonner';

export default function Home() {
  const navigate = useNavigate();

  useBarcode(handleBarcodeScan);

  let cheatActive = false;
  window.addEventListener(
    'cheatCode',
    (e) => {
      if (!cheatActive) cheatActive = true;
    },
    { once: true },
  );
  cheatCode();

  async function handleBarcodeScan(value: string) {
    if (!value) return;

    const [scannedProduct] =
      (await getData<itemsView[]>('items_view?Barcode=' + value)) || [];

    if (!scannedProduct) return toast.warning('Produktet kunne ikke findes');

    if (scannedProduct.Status == 'Available') {
      navigate(`/udlaan/new?item=${scannedProduct.UUID}`);
      return;
    }

    if (scannedProduct.Status == 'Lent') {
      const item_from_loan = await getData<itemsFromLoan[]>(
        `items_from_loans?UUID=${scannedProduct.UUID}&Returneret=null`,
      );

      if (!item_from_loan?.length) {
        toast.error(
          'Produktet er lånt ud, men kunne ikke findes på et aktivt lån',
        );
        return;
      }

      return navigate(
        `/udlaan/${item_from_loan[0].loan_id}/returner?item=${scannedProduct.UUID}`,
      );
    }

    navigate(`/produkter/${scannedProduct.UUID}`);
  }

  <img src="/nyanCat.gif" alt="nyan cat" />;
  if (cheatActive) return;

  return (
    <div className="flex max-h-screen flex-col items-center gap-2 pt-16">
      <h1 className="text-[3rem]">Velkommen til helpdesk'en</h1>
      <p className="text-[1.2rem] text-foreground2">
        Hvordan kan vi hjælpe dig i dag?
      </p>
      <img
        className="h-full w-3/5 object-cover"
        src="svg/welcome.svg"
        alt="Welcome"
      />
    </div>
  );
}

// frontend/udlånssystem/src/pages/Home.svelte
<script>
  import getData from "../data/getData";
  import { cheatCode } from "../services/cheatCode.js";

  let cheatActive = false;
  window.addEventListener(
    "cheatCode",
    (e) => {
      if (!cheatActive) {
        cheatActive = true;
      }
      //remove event listener
    },
    { once: true }
  );
  cheatCode();
  import goToPath from "../services/goToPath";
  import { barcodeStore, barcodeBuilderTimeOut } from "../stores/barcodeStore";
  async function handleBarcodeScan(value) {
    if (!value) return;
    if (Date.now() - $barcodeBuilderTimeOut > 100) {
      return;
    }

    const [scannedProduct] = await getData("items_view?Barcode=" + value);

    if (!scannedProduct) return alert("Produktet kunne ikke findes");

    if (scannedProduct.Status == "Available") {
      goToPath(`/udlaan/new?item=${scannedProduct.UUID}`);
      return;
    }

    if (scannedProduct.Status == "Lent") {
      const item_from_loan = await getData(
        `items_from_loans?UUID=${scannedProduct.UUID}&Returneret=null`
      );

      barcodeStore.set(value);

      return goToPath(`/udlaan/${item_from_loan.loan_id}/returner`);
    }

    goToPath(`/produkter/${scannedProduct.UUID}`);
  }
  $: handleBarcodeScan($barcodeStore);
</script>

{#if cheatActive}
  <img src="/nyanCat.gif" alt="nyan cat" />
{:else}
  <div class="content">
    <h1>Velkommen til helpdesk'en</h1>
    <p>Hvordan kan vi hjælpe dig i dag?</p>
    <img class="svg" src="svg/welcome.svg" alt="Welcome" />
  </div>
{/if}

<style>
  .svg {
    width: 60%;
  }
  .content {
    padding-top: 4rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    max-height: 100vh;
  }
  p {
    color: var(--text2);
    font-size: 1.2rem;
  }
  h1 {
    font-size: 3rem;
  }
  img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
</style>
