// frontend/udlånssystem/src/App.tsx
import { createContext, useState } from 'react';
import { Outlet, Route, Routes } from 'react-router-dom';

import Nav from '@components/Nav';
import Breadcrumbs from '@components/breadcrumbs';
import { Toaster } from '@components/ui/sonner';

import Dashboard from '@pages/Dashboard';
import Error404 from '@pages/Error404';
import Feedback from '@pages/Feedback';
import Home from '@pages/Home';
import Login from '@pages/Login';
import Chat from '@pages/chat';
import loanReturn from '@pages/loans/return/return';
import Notifications from '@pages/notifications';

import brands from '@pages/brands/index';
import categories from '@pages/categories/index';
import loans from '@pages/loans/index';
import productStatus from '@pages/productStatus/index';
import productTypes from '@pages/productTypes/index';
import products from '@pages/products/index';

import brandsEdit from '@pages/brands/edit';
import categoriesEdit from '@pages/categories/edit';
import loansEdit from '@pages/loans/edit';
import productStatusEdit from '@pages/productStatus/edit';
import productTypesEdit from '@pages/productTypes/edit';
import productsEdit from '@pages/products/edit';

import brandsNew from '@pages/brands/new';
import categoriesNew from '@pages/categories/new';
import loansNew from '@pages/loans/new';
import productStatusNew from '@pages/productStatus/new';
import productTypesNew from '@pages/productTypes/new';
import productsNew from '@pages/products/new';

import './axios.config';

export const CurrentUserContext = createContext<CurrentUserContextType>({
  currentUser: undefined,
} as CurrentUserContextType);

function Layout() {
  const [currentUser, setCurrentUser] = useState<userState>();

  return (
    <CurrentUserContext.Provider
      value={{
        currentUser,
        setCurrentUser,
      }}
    >
      <Toaster theme="dark" closeButton position="bottom-center" />
      {currentUser ? (
        <div className="grid h-screen grid-cols-[auto_1fr] bg-base-100">
          <header className="h-screen w-nav bg-nav">
            <Nav />
          </header>
          <main className="relative grid h-screen grid-rows-[50px_1fr] overflow-y-auto">
            <Breadcrumbs />

            <div className="h-full overflow-y-hidden">
              <Outlet />
            </div>
          </main>
        </div>
      ) : (
        <Login />
      )}
    </CurrentUserContext.Provider>
  );
}

export default function App() {
  return (
    <Routes>
      <Route path="/" element={<Layout />}>
        <Route Component={Error404} />
        <Route path="/" Component={Home} />
        <Route path="hjem" Component={Home} />

        <Route path="dashboard" Component={Dashboard} />
        <Route path="notifikationer" Component={Notifications} />
        <Route path="chat" Component={Chat} />
        <Route path="feedback" Component={Feedback} />

        <Route path="brands" Component={brands} />
        <Route path="kategorier" Component={categories} />
        <Route path="udlaan" Component={loans} />
        <Route path="produktstatusser" Component={productStatus} />
        <Route path="produkttyper" Component={productTypes} />
        <Route path="produkter" Component={products} />

        <Route path="brands/:id" Component={brandsEdit} />
        <Route path="kategorier/:id" Component={categoriesEdit} />
        <Route path="produkter/:id" Component={productsEdit} />
        <Route path="produkttyper/:id" Component={productTypesEdit} />
        <Route path="udlaan/:id" Component={loansEdit} />
        <Route path="produktstatusser/:id" Component={productStatusEdit} />

        <Route path="produkter/new" Component={productsNew} />
        <Route path="brands/new" Component={brandsNew} />
        <Route path="kategorier/new" Component={categoriesNew} />
        <Route path="produkttyper/new" Component={productTypesNew} />
        <Route path="udlaan/new" Component={loansNew} />
        <Route path="produktstatusser/new" Component={productStatusNew} />

        <Route path="udlaan/:id/returner" Component={loanReturn} />
      </Route>
    </Routes>
  );
}

// frontend/udlånssystem/src/App.svelte
<script lang="ts">
  import { currentUser, login } from "./services/login";
  import { Router, Route } from "svelte-routing";
  import axios from "axios";

  //login page
  import NotLoggedIn from "./pages/login/index.svelte";

  //pages import
  import Nav from "./components/Nav.svelte";
  import Home from "./pages/Home.svelte";
  import Users from "./pages/users/index.svelte";
  import Error404 from "./pages/Error404.svelte";
  import Products from "./pages/products/index.svelte";
  import Dashboard from "./pages/dashboard/index.svelte";
  import Brands from "./pages/brands/index.svelte";
  import CategoriesGroups from "./pages/categories/index.svelte";
  import Locations from "./pages/locations/index.svelte";
  import ProductTypes from "./pages/productTypes/index.svelte";
  import Help from "./pages/help/index.svelte";
  import Notifications from "./pages/notifications/index.svelte";
  import Chat from "./pages/chat/index.svelte";
  import Breadcrumps from "./components/breadcrumps.svelte";
  import Loans from "./pages/loans/index.svelte";
  import Loading from "./pages/Loading.svelte";

  //dynamic pages import
  import usersEdit from "./pages/users/edit.svelte";
  import productsEdit from "./pages/products/edit.svelte";
  import brandsEdit from "./pages/brands/edit.svelte";
  import categoriesEdit from "./pages/categories/edit.svelte";
  import locationsEdit from "./pages/locations/edit.svelte";
  import productTypesEdit from "./pages/productTypes/edit.svelte";
  import loansEdit from "./pages/loans/edit.svelte";

  //new pages import
  import usersNew from "./pages/users/new.svelte";
  import productsNew from "./pages/products/new.svelte";
  import brandsNew from "./pages/brands/new.svelte";
  import categoriesNew from "./pages/categories/new.svelte";
  import locationsNew from "./pages/locations/new.svelte";
  import productTypesNew from "./pages/productTypes/new.svelte";
  import loansNew from "./pages/loans/new.svelte";

  // $: console.log("user", $currentUser);

  $: loading = true;
  login().then(() => {
    loading = false;
  });

  import "./axiosConfig.js"

  import { path } from "./stores/pathStore";
  import { onMount } from "svelte";

  onMount(() => {
    path.update(() => {
      return window.location.pathname;
    });
    //set theme
    if (localStorage.getItem("theme") === "dark") {
      document.documentElement.className = "dark";
    } else {
      document.documentElement.className = "light";
    }
  });
  $: loggedIn = $currentUser;

  //on page change update path
  window.onpopstate = function (event) {
    path.update(() => {
      return window.location.pathname;
    });
  };
</script>

<!-- While in development disable login -->
<!-- {#if true} -->
{#if loggedIn}
  <div class="app">
    <Router>
      <!-- navigation -->
      <header>
        <Nav />
      </header>
      <!-- routes -->
      <main>
        <div class="breadcrumps">
          <Breadcrumps />
        </div>
        <div class="main">
          <!-- main routes -->
          <Route component={Error404} />
          <Route path="/" component={Home} />
          <Route path="hjem" component={Home} />

          <!-- pages -->
          <Route path="brugere" component={Users} />
          <Route path="dashboard" component={Dashboard} />
          <Route path="produkter" component={Products} />
          <Route path="brands" component={Brands} />
          <Route path="produktkategorier" component={CategoriesGroups} />
          <Route path="lokaliteter" component={Locations} />
          <Route path="produkttyper" component={ProductTypes} />
          <Route path="notifikationer" component={Notifications} />
          <Route path="chat" component={Chat} />
          <Route path="udlaan" component={Loans} />
          <Route path="help" component={Help} />

          <!-- dynamic routs -->
          <Route path="brugere/:id" component={usersEdit} />
          <Route path="produkter/:id" component={productsEdit} />
          <Route path="brands/:id" component={brandsEdit} />
          <Route path="produktkategorier/:id" component={categoriesEdit} />
          <Route path="lokaliteter/:id" component={locationsEdit} />
          <Route path="produkttyper/:id" component={productTypesEdit} />
          <Route path="udlaan/:id" component={loansEdit} />

          <!-- new routes -->
          <Route path="brugere/new" component={usersNew} />
          <Route path="produkter/new" component={productsNew} />
          <Route path="brands/new" component={brandsNew} />
          <Route path="produktkategorier/new" component={categoriesNew} />
          <Route path="lokaliteter/new" component={locationsNew} />
          <Route path="produkttyper/new" component={productTypesNew} />
          <Route path="udlaan/new" component={loansNew} />
        </div>
      </main>
    </Router>
  </div>
{:else if loading}
  <Loading />
{:else}
  <NotLoggedIn />
{/if}

<style>
  .app {
    display: grid;
    grid-template-columns: auto 1fr;
    height: 100vh;
    background-color: var(--bg1);
  }
  header {
    background: var(--nav);
    width: 20rem;
    height: 100vh;
  }
  main {
    overflow-y: hidden;
    height: 100vh;
    overflow-y: auto;
    position: relative;
    display: grid;
    grid-template-rows: 50px 1fr;
  }
  .breadcrumps {
    width: 100%;
    padding: 0.5rem;
    position: sticky;
    top: 0;
    z-index: 99999999999999999999999999999999999;
  }
  .main {
    overflow-y: hidden;
    height: 100%;
  }
</style>
