// frontend/udlånssystem/src/pages/products/edit.tsx
import { Link, useParams } from 'react-router-dom';

import useData from '@hooks/useData';

import EditLayout from '@layouts/edit';

import { LoanHistory, fields, zodSchema } from './util';

import '@styles/productsEdit.css';

interface itemModelWithItemsInLoan extends itemModel {
  items_in_loan: itemInLoanModel[];
}

export default function Edit() {
  const { id } = useParams();
  const [item] = useData<itemModelWithItemsInLoan>('items', undefined, id);
  const [itemInLoan] = useData<itemInLoanModel[]>(
    'items_in_loan?item_id=' + id,
    { withHeaders: false },
  );

  if (!item) return null;

  let loanText = item.product_status_id === 1 ? 'Opret lån' : 'Gå til lån';
  let to = item.product_status_id === 1 ? '/udlaan/new?item=' + id : '';

  if (itemInLoan && itemInLoan.length > 0 && !itemInLoan[0]?.date_returned) {
    to = '/udlaan/' + itemInLoan[0].loan_id;
  }

  return (
    <EditLayout
      table="items"
      fields={fields}
      zodSchema={zodSchema}
      panelSlot={
        <>
          <div className="flex flex-col items-center gap-3 overflow-hidden">
            <h1>Lånehistorik:</h1>
            {item?.items_in_loan?.length > 0 ? (
              <ul className="loanHistoryList">
                {item?.items_in_loan
                  .reverse()
                  .map((item: itemInLoanModel | any, i: number) => {
                    const loanHistory = new LoanHistory(item);
                    return (
                      <Link
                        key={i}
                        className={`${loanHistory.isActive()} loanHistoryItem`}
                        to={`/udlaan/${item.loan_id}`}
                      >
                        <p>{loanHistory.date()}</p>
                        <p>{loanHistory.time()}</p>
                        <p>{loanHistory.user()}</p>
                      </Link>
                    );
                  })}
              </ul>
            ) : (
              <p>Ingen lånehistorik</p>
            )}
          </div>

          <Link
            className="mt-auto flex h-8 w-full min-w-8 items-center justify-center rounded-[10px] border-[1px] border-foreground bg-none text-foreground"
            to={to}
          >
            {loanText}
          </Link>
        </>
      }
    ></EditLayout>
  );
}

// frontend/udlånssystem/src/pages/products/edit.svelte
<script lang="ts">
  import EditLayout from "@layouts/edit.svelte";
  import { zodSchema, fields, LoanHistory } from "./util";
  import { onMount } from "svelte";
  import getData from "@data/getData";

  export let id: number;

  $: items = [] as any;

  onMount(async () => {
    items = await getData("items", id);
  });

  let show = false;
</script>

<EditLayout table="items" page_name="Produkter" UUID={id} {fields} {zodSchema}>
  <div
    slot="edit-panel"
    class="flex flex-col items-center gap-3 overflow-hidden"
  >
    <h1>Lånehistorik:</h1>
    {#if items?.items_in_loan?.length > 0}
      <ul class="loanHistoryList">
        {#each items?.items_in_loan.reverse() as item}
          <a
            class={`${new LoanHistory(item).isActive()} loanHistoryItem`}
            href={`/udlaan/${item.loan_id}`}
          >
            <p>{new LoanHistory(item).date()}</p>
            <p>{new LoanHistory(item).time()}</p>
            <p>{new LoanHistory(item).user()}</p>
          </a>
        {/each}
      </ul>
    {:else}
      <p>Ingen lånehistorik</p>
    {/if}
  </div>
</EditLayout>

<style>
  .loanHistoryList {
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
    text-align: center;
  }

  .loanHistoryItem {
    width: 100%;
    min-height: 2rem;
    padding: 0.6rem;
    color: var(--text1);
    background: transparent;
    border: 3px solid var(--text1);
    border-radius: 10px;
  }

  .active {
    border-color: var(--p);
  }
</style>
